#!/usr/bin/env bash

AGENTS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd $AGENTS_DIR

sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  just \
  ruby-full \
  libclang-dev \
  capnproto libcapnp-dev

rustup component add rustfmt

pushd ..
  just build-extension
popd
