#!/usr/bin/env bash

AGENTS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd $AGENTS_DIR

sudo apt-get update
sudo apt-get install -y --no-install-recommends just ruby-full

pushd ..
  just build-extension
popd
